### ISSUE TITLE
How to change width of page?

### ISSUE THREAD

**Issue by poVoq** [fardina/q2a-child-theme#1]
I am trying to change the page width of a SnowFlat/SnowLight themed page by adding this code:

> .qa-body-wrapper {
> width: 90%;
> }

But it doesn't seem to do anything. And tips?

**Comment by fardina** [comment]
@poVoq this should work. Please try `ctrl`+`f5` to refresh the page.

**Comment by poVoq** [comment]
Sorry, that doesn't work either. I also tried opening the page in an private browser window to avoid caching issues.

**Comment by fardina** [comment]
@poVoq But I tested this in my website and worked. please make sure your `child-theme-layer.php` file content is like:
```php
<?php
class qa_html_theme_layer extends qa_html_theme_base
{
	function head_css() {
		parent::head_css();
		if (qa_opt('child_theme_on')) { // first check the feature is turned on
		$this->output('<LINK REL="stylesheet" TYPE="text/css" HREF="'.QA_HTML_THEME_LAYER_URLTOROOT.'child-theme.css"/>');
		}
		
       }
}
```

**Comment by poVoq** [comment]
No, mine looks like this... it is an older version?

```
<?php

class qa_html_theme_layer extends qa_html_theme_base
{
	function head_css() {
		if (qa_opt('child_theme_on')) { // first check the feature is turned on
		$this->output('<LINK REL="stylesheet" TYPE="text/css" HREF="'.QA_HTML_THEME_LAYER_URLTOROOT.'child-theme.css"/>');
		}
        parent::head_css();
		
       }
}
```

**Comment by fardina** [comment]
Yes, pleaae change it and then works fine for you.

**Comment by poVoq** [comment]
Hmm, I updated to the latest github master (V1.1), which include the change you mentioned, but it still isn't working.
Are you using the same theme (snowlight)?

**Comment by fardina** [comment]
@poVoq No I don't. I am using the snowflat theme. But it should work with snowlight too. I didn't test that.

**Comment by poVoq** [comment]
Ehh, it works when I remove the:
// your css styles here
at the top.

Isn't that just a comment?

**Comment by poVoq** [comment]
However, I should add that the above messed up the mobile view and this seems better:
@media (min-width: 1044px) {
	.qa-body-wrapper {
		width: 1224px;
	}
}
